"""
Ticker-to-company-name mapping for dashboard display.
Short names only (~20 chars max).
"""

TICKER_NAMES = {
    # ── ETFs ──────────────────────────────────────────────────
    "QQQ": "Nasdaq 100",
    "BTC-USD": "Bitcoin",
    "ARKK": "ARK Innovation",
    "IWM": "Russell 2000",
    "XLC": "Comm Services",
    "XLY": "Consumer Discret",
    "TLT": "20+ Yr Treasury",
    "LQD": "IG Corp Bonds",
    "XLE": "Energy Sector",
    "DBC": "Broad Commodities",
    "GCC": "Commodity Index",
    "LIT": "Lithium & Battery",
    "XLF": "Financials",
    "XLI": "Industrials",
    "XLB": "Materials",
    "USO": "Crude Oil",
    "XOP": "Oil & Gas E&P",
    "FCG": "Natural Gas",
    "VNQ": "Real Estate",
    "PAVE": "Infrastructure",
    "VTV": "Value",
    "EWX": "EM Small Cap",
    "IWD": "Russell Value",
    "VWO": "EM Stocks",
    "GLD": "Gold",
    "DBA": "Agriculture",
    "REMX": "Rare Earth Metals",
    "URA": "Uranium",
    "TIP": "TIPS",
    "VTIP": "Short-Term TIPS",
    "XLV": "Healthcare",
    "XLU": "Utilities",
    "VGLT": "Long-Term Treasury",
    "IEF": "7-10 Yr Treasury",
    "MUB": "Muni Bonds",
    "XLP": "Consumer Staples",
    "VUG": "Growth",
    "VIXY": "VIX Futures",
    # ── BTC Proxy Basket ──────────────────────────────────────
    "MSTR": "MicroStrategy",
    "STRIVE": "Strive Bitcoin",
    "SBET": "SharpLink Gaming",
    "MARA": "Marathon Digital",
    "CLSK": "CleanSpark",
    "RIOT": "Riot Platforms",
    "BITF": "Bitfarms",
    "CIFR": "Cipher Mining",
    "IREN": "Iris Energy",
    "CORZ": "Core Scientific",
    "HUT": "Hut 8 Mining",
    "BTDR": "Bitdeer Tech",
    "BTBT": "Bit Digital",
    "WULF": "TeraWulf",
    "HIVE": "HIVE Digital",
    "ASST": "Asset Entities",
    "UPXI": "Upexi",
    "AVX": "AVAX One Tech",
    "DFDV": "DeFi Dev Corp",
    "COIN": "Coinbase",
    "GLXY": "Galaxy Digital",
    "CRCL": "Circle (USDC)",
    "HOOD": "Robinhood",
    "BLSH": "Blockstream",
    "CAN": "Canaan",
    "SQ": "Block (Square)",
    # ── XLE Constituents ──────────────────────────────────────
    "XOM": "ExxonMobil",
    "CVX": "Chevron",
    "COP": "ConocoPhillips",
    "WMB": "Williams Cos",
    "EOG": "EOG Resources",
    "MPC": "Marathon Petroleum",
    "PSX": "Phillips 66",
    "SLB": "Schlumberger",
    "VLO": "Valero Energy",
    "KMI": "Kinder Morgan",
    "BKR": "Baker Hughes",
    "OKE": "ONEOK",
    "EQT": "EQT Corp",
    "TRGP": "Targa Resources",
    "OXY": "Occidental",
    "FANG": "Diamondback Energy",
    "EXE": "Expand Energy",
    "DVN": "Devon Energy",
    "HAL": "Halliburton",
    "CTRA": "Coterra Energy",
    "TPL": "Texas Pacific Land",
    "APA": "APA Corp",
    # ── LIT Constituents ──────────────────────────────────────
    "RIO": "Rio Tinto",
    "ALB": "Albemarle",
    "SQM": "SQM (Lithium)",
    "TSLA": "Tesla",
    "ENS": "EnerSys",
    "LAC": "Lithium Americas",
    "SGML": "Sigma Lithium",
    # ── XLF Constituents ──────────────────────────────────────
    "BRK.B": "Berkshire Hathaway",
    "JPM": "JPMorgan Chase",
    "V": "Visa",
    "MA": "Mastercard",
    "BAC": "Bank of America",
    "WFC": "Wells Fargo",
    "GS": "Goldman Sachs",
    "SPGI": "S&P Global",
    "AXP": "American Express",
    "PGR": "Progressive",
    "MS": "Morgan Stanley",
    "FI": "Fiserv",
    "C": "Citigroup",
    "BLK": "BlackRock",
    "MMC": "Marsh McLennan",
    "CB": "Chubb",
    "ICE": "Intercontinental Exch",
    "SCHW": "Charles Schwab",
    "CME": "CME Group",
    "AON": "Aon",
    "MCO": "Moody's",
    "COF": "Capital One",
    "USB": "US Bancorp",
    "AJG": "Arthur J Gallagher",
    "PNC": "PNC Financial",
    "TFC": "Truist Financial",
    "AIG": "AIG",
    "TRV": "Travelers",
    "AFL": "Aflac",
    "MET": "MetLife",
    "BK": "BNY Mellon",
    "ALL": "Allstate",
    "ACGL": "Arch Capital",
    "DFS": "Discover Financial",
    "FIS": "Fidelity Natl Info",
    "NDAQ": "Nasdaq Inc",
    "WTW": "Willis Towers Watson",
    "FITB": "Fifth Third Bank",
    "STT": "State Street",
    "RF": "Regions Financial",
    "HBAN": "Huntington Banc",
    "NTRS": "Northern Trust",
    "CINF": "Cincinnati Finl",
    "CFG": "Citizens Financial",
    "KEY": "KeyCorp",
    "SYF": "Synchrony Finl",
    "BRO": "Brown & Brown",
    "RJF": "Raymond James",
    "MKTX": "MarketAxess",
    "ERIE": "Erie Indemnity",
    # ── XLI Constituents ──────────────────────────────────────
    "GE": "GE Aerospace",
    "CAT": "Caterpillar",
    "RTX": "RTX (Raytheon)",
    "UNP": "Union Pacific",
    "HON": "Honeywell",
    "ETN": "Eaton",
    "ADP": "ADP",
    "BA": "Boeing",
    "DE": "Deere & Co",
    "LMT": "Lockheed Martin",
    "UBER": "Uber",
    "TT": "Trane Technologies",
    "WM": "Waste Management",
    "GD": "General Dynamics",
    "ITW": "Illinois Tool Works",
    "NOC": "Northrop Grumman",
    "EMR": "Emerson Electric",
    "CSX": "CSX Corp",
    "PH": "Parker Hannifin",
    "FDX": "FedEx",
    "CTAS": "Cintas",
    "CARR": "Carrier Global",
    "NSC": "Norfolk Southern",
    "GEV": "GE Vernova",
    "PCAR": "PACCAR",
    "AXON": "Axon Enterprise",
    "FAST": "Fastenal",
    "AME": "Ametek",
    "CMI": "Cummins",
    "VRSK": "Verisk Analytics",
    "RSG": "Republic Services",
    "ODFL": "Old Dominion",
    "TDG": "TransDigm",
    "CPRT": "Copart",
    "PWR": "Quanta Services",
    "IR": "Ingersoll Rand",
    "HWM": "Howmet Aerospace",
    "ROK": "Rockwell Automat",
    "DAL": "Delta Air Lines",
    "WAB": "Wabtec",
    "DOV": "Dover Corp",
    "XYL": "Xylem",
    "OTIS": "Otis Worldwide",
    "UAL": "United Airlines",
    "GWW": "Grainger",
    "SWK": "Stanley Black Decker",
    "LUV": "Southwest Airlines",
    "J": "Jacobs Solutions",
    # ── XLB Constituents ──────────────────────────────────────
    "LIN": "Linde",
    "NEM": "Newmont",
    "FCX": "Freeport-McMoRan",
    "SHW": "Sherwin-Williams",
    "CRH": "CRH",
    "APD": "Air Products",
    "ECL": "Ecolab",
    "DD": "DuPont",
    "CTVA": "Corteva",
    "DOW": "Dow Inc",
    "NUE": "Nucor",
    "VMC": "Vulcan Materials",
    "MLM": "Martin Marietta",
    "PPG": "PPG Industries",
    "IFF": "Intl Flavors",
    "STLD": "Steel Dynamics",
    "BALL": "Ball Corp",
    "PKG": "Packaging Corp",
    "LYB": "LyondellBasell",
    "IP": "Intl Paper",
    "FMC": "FMC Corp",
    "CE": "Celanese",
    "EMN": "Eastman Chemical",
    "CF": "CF Industries",
    "MOS": "Mosaic Co",
    "AMCR": "Amcor",
    # ── XOP / FCG Extra Constituents ──────────────────────────
    "VG": "Vonage/Ericsson",
    "CRC": "California Res",
    "CHRD": "Chord Energy",
    "HES": "Hess Corp",
    "PBF": "PBF Energy",
    "AR": "Antero Resources",
    "DK": "Delek US",
    "MTDR": "Matador Resources",
    "RRC": "Range Resources",
    "PR": "Permian Resources",
    "DINO": "HF Sinclair",
    "SM": "SM Energy",
    "OVV": "Ovintiv",
    "MGY": "Magnolia Oil & Gas",
    "MUR": "Murphy Oil",
    "AM": "Antero Midstream",
    "CNX": "CNX Resources",
    # ── VNQ Constituents ──────────────────────────────────────
    "PLD": "Prologis",
    "AMT": "American Tower",
    "EQIX": "Equinix",
    "WELL": "Welltower",
    "DLR": "Digital Realty",
    "SPG": "Simon Property",
    "PSA": "Public Storage",
    "CCI": "Crown Castle",
    "CBRE": "CBRE Group",
    "O": "Realty Income",
    "VICI": "VICI Properties",
    "EXR": "Extra Space Storage",
    "IRM": "Iron Mountain",
    "SBAC": "SBA Communications",
    "AVB": "AvalonBay",
    "WY": "Weyerhaeuser",
    "ARE": "Alexandria RE",
    "EQR": "Equity Residential",
    "INVH": "Invitation Homes",
    "ESS": "Essex Property",
    "MAA": "Mid-America Apt",
    "KIM": "Kimco Realty",
    "REG": "Regency Centers",
    "UDR": "UDR Inc",
    "CPT": "Camden Property",
    "HST": "Host Hotels",
    "DOC": "Healthpeak Prop",
    "CUBE": "CubeSmart",
    "BXP": "BXP (Boston Prop)",
    "SUI": "Sun Communities",
    # ── PAVE Extra Constituents ───────────────────────────────
    "URI": "United Rentals",
    "EME": "EMCOR Group",
    "WMS": "Advanced Drainage",
    "GNRC": "Generac",
    "FLR": "Fluor Corp",
    "MAS": "Masco Corp",
    "RS": "Reliance Steel",
    "MTZ": "MasTec",
    "CLF": "Cleveland-Cliffs",
    "CSL": "Carlisle Cos",
    "TREX": "Trex Co",
    "ACM": "AECOM",
    "AWI": "Armstrong World",
    "FIX": "Comfort Systems",
    # ── VTV Extra Constituents ────────────────────────────────
    "UNH": "UnitedHealth",
    "JNJ": "Johnson & Johnson",
    "PG": "Procter & Gamble",
    "HD": "Home Depot",
    "ABBV": "AbbVie",
    "MRK": "Merck",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "CSCO": "Cisco",
    "WMT": "Walmart",
    "ABT": "Abbott Labs",
    "PM": "Philip Morris",
    "DIS": "Disney",
    "CMCSA": "Comcast",
    "VZ": "Verizon",
    "T": "AT&T",
    "NEE": "NextEra Energy",
    "DHR": "Danaher",
    "BMY": "Bristol-Myers",
    "INTC": "Intel",
    # ── REMX Extra Constituents ───────────────────────────────
    "MP": "MP Materials",
    "UUUU": "Energy Fuels",
    "TREM": "Tremor Video",
    "CENX": "Century Aluminum",
    "ALTM": "Altus Midstream",
    # ── URA Constituents ──────────────────────────────────────
    "CCJ": "Cameco",
    "NXE": "NexGen Energy",
    "UEC": "Uranium Energy",
    "DNN": "Denison Mines",
    "SRUUF": "Sprott Physical U",
    "ENCUF": "enCore Energy",
    "LEU": "Centrus Energy",
    "SMR": "NuScale Power",
    "LTBR": "Lightbridge",
    "URG": "Ur-Energy",
    # ── XLV Constituents ──────────────────────────────────────
    "LLY": "Eli Lilly",
    "TMO": "Thermo Fisher",
    "AMGN": "Amgen",
    "PFE": "Pfizer",
    "ISRG": "Intuitive Surgical",
    "BSX": "Boston Scientific",
    "VRTX": "Vertex Pharma",
    "SYK": "Stryker",
    "GILD": "Gilead Sciences",
    "MDT": "Medtronic",
    "REGN": "Regeneron",
    "ELV": "Elevance Health",
    "ZTS": "Zoetis",
    "BDX": "Becton Dickinson",
    "CI": "Cigna",
    "HCA": "HCA Healthcare",
    "EW": "Edwards Lifesci",
    "IDXX": "IDEXX Labs",
    "A": "Agilent Tech",
    "MCK": "McKesson",
    "IQV": "IQVIA",
    "GEHC": "GE HealthCare",
    "RMD": "ResMed",
    "DXCM": "DexCom",
    "MTD": "Mettler-Toledo",
    "COO": "CooperCompanies",
    "HOLX": "Hologic",
    "TFX": "Teleflex",
    "WST": "West Pharma",
    "ALGN": "Align Technology",
    "TECH": "Bio-Techne",
    "PODD": "Insulet",
    "BAX": "Baxter Intl",
    "VTRS": "Viatris",
    "ZBH": "Zimmer Biomet",
    "HSIC": "Henry Schein",
    "CRL": "Charles River Labs",
    "XRAY": "Dentsply Sirona",
    "DGX": "Quest Diagnostics",
    "LH": "Labcorp",
    "INCY": "Incyte",
    "BIIB": "Biogen",
    "MOH": "Molina Healthcare",
    "CNC": "Centene",
    "HUM": "Humana",
    "CAH": "Cardinal Health",
    # ── XLU Constituents ──────────────────────────────────────
    "SO": "Southern Co",
    "DUK": "Duke Energy",
    "CEG": "Constellation Energy",
    "VST": "Vistra",
    "SRE": "Sempra",
    "AEP": "Amer Electric Power",
    "D": "Dominion Energy",
    "PCG": "PG&E",
    "PEG": "PSEG",
    "EXC": "Exelon",
    "XEL": "Xcel Energy",
    "ED": "Con Edison",
    "WEC": "WEC Energy",
    "ES": "Eversource",
    "AWK": "American Water",
    "ETR": "Entergy",
    "FE": "FirstEnergy",
    "PPL": "PPL Corp",
    "CMS": "CMS Energy",
    "ATO": "Atmos Energy",
    "CNP": "CenterPoint",
    "EVRG": "Evergy",
    "NI": "NiSource",
    "AES": "AES Corp",
    "LNT": "Alliant Energy",
    "NRG": "NRG Energy",
    "PNW": "Pinnacle West",
    "DTE": "DTE Energy",
    "OGE": "OGE Energy",
    "BKH": "Black Hills",
    # ── QQQ Constituents ──────────────────────────────────────
    "NVDA": "Nvidia",
    "MSFT": "Microsoft",
    "AAPL": "Apple",
    "AVGO": "Broadcom",
    "AMZN": "Amazon",
    "META": "Meta Platforms",
    "GOOGL": "Alphabet (A)",
    "GOOG": "Alphabet (C)",
    "NFLX": "Netflix",
    "PLTR": "Palantir",
    "COST": "Costco",
    "TMUS": "T-Mobile",
    "AMD": "AMD",
    "APP": "AppLovin",
    "INTU": "Intuit",
    "MU": "Micron",
    "SHOP": "Shopify",
    "QCOM": "Qualcomm",
    "BKNG": "Booking Holdings",
    "TXN": "Texas Instruments",
    "LRCX": "Lam Research",
    "AMAT": "Applied Materials",
    "ADBE": "Adobe",
    "KLAC": "KLA Corp",
    "PANW": "Palo Alto Networks",
    "MELI": "MercadoLibre",
    "CRWD": "CrowdStrike",
    "ADI": "Analog Devices",
    "DASH": "DoorDash",
    "SBUX": "Starbucks",
    "CDNS": "Cadence Design",
    "ORLY": "O'Reilly Auto",
    "SNPS": "Synopsys",
    "PDD": "PDD Holdings",
    "ASML": "ASML",
    "MDLZ": "Mondelez",
    "MAR": "Marriott",
    "MRVL": "Marvell Tech",
    "TRI": "Thomson Reuters",
    "ADSK": "Autodesk",
    "PYPL": "PayPal",
    "MNST": "Monster Beverage",
    "FTNT": "Fortinet",
    "NXPI": "NXP Semi",
    "ROP": "Roper Tech",
    "WDAY": "Workday",
    "ABNB": "Airbnb",
    "EA": "Electronic Arts",
    "ROST": "Ross Stores",
    "TTWO": "Take-Two",
    "DDOG": "Datadog",
    "ZS": "Zscaler",
    "PAYX": "Paychex",
    "AZN": "AstraZeneca",
    "CCEP": "Coca-Cola Europac",
    "CHTR": "Charter Comm",
    "CSGP": "CoStar Group",
    "KDP": "Keurig Dr Pepper",
    "MCHP": "Microchip Tech",
    "CTSH": "Cognizant",
    "KHC": "Kraft Heinz",
    "TEAM": "Atlassian",
    "CDW": "CDW Corp",
    "GFS": "GlobalFoundries",
    "LULU": "Lululemon",
    "ON": "ON Semiconductor",
    "ARM": "Arm Holdings",
    "TTD": "The Trade Desk",
    # ── ARKK Constituents ─────────────────────────────────────
    "CRSP": "CRISPR Therapeutics",
    "TEM": "Tempus AI",
    "ROKU": "Roku",
    "BEAM": "Beam Therapeutics",
    "TER": "Teradyne",
    "TWST": "Twist Bioscience",
    "ACHR": "Archer Aviation",
    "TXG": "10x Genomics",
    "BMNR": "Bitmine Immersion",
    "CRWV": "CrowdStrike (W)",
    "NTLA": "Intellia Therapeut",
    "TSM": "TSMC",
    "BIDU": "Baidu",
    "NTRA": "Natera",
    "RXRX": "Recursion Pharma",
    "BWXT": "BWX Technologies",
    "KTOS": "Kratos Defense",
    "ILMN": "Illumina",
    "VCYT": "Veracyte",
    "WGS": "GeneDx",
    "BABA": "Alibaba",
    "SOFI": "SoFi Technologies",
    "PD": "PagerDuty",
    "PACB": "PacBio",
    "CERS": "Cerus Corp",
    "RBLX": "Roblox",
    # ── XLC Constituents ──────────────────────────────────────
    "WBD": "Warner Bros Disc",
    "OMC": "Omnicom",
    "LYV": "Live Nation",
    "FOXA": "Fox Corp (A)",
    "TKO": "TKO Group",
    "NWSA": "News Corp (A)",
    "FOX": "Fox Corp (B)",
    "MTCH": "Match Group",
    "PSKY": "ParaZero",
    "NWS": "News Corp (B)",
    # ── XLY Constituents ──────────────────────────────────────
    "MCD": "McDonald's",
    "TJX": "TJX Companies",
    "LOW": "Lowe's",
    "NKE": "Nike",
    "GM": "General Motors",
    "RCL": "Royal Caribbean",
    "HLT": "Hilton",
    "AZO": "AutoZone",
    "F": "Ford",
    "CMG": "Chipotle",
    "DHI": "D.R. Horton",
    "YUM": "Yum! Brands",
    "EBAY": "eBay",
    "GRMN": "Garmin",
    "EXPE": "Expedia",
    "DECK": "Deckers Outdoor",
    "LEN": "Lennar",
    "POOL": "Pool Corp",
    "NVR": "NVR Inc",
    "LVS": "Las Vegas Sands",
    "APTV": "Aptiv",
    "BBY": "Best Buy",
    "DRI": "Darden Restaurants",
    "PHM": "PulteGroup",
    "ULTA": "Ulta Beauty",
    "DPZ": "Domino's Pizza",
    "GPC": "Genuine Parts",
    "TPR": "Tapestry",
    "WSM": "Williams-Sonoma",
    "CCL": "Carnival",
    "TSCO": "Tractor Supply",
    "KMX": "CarMax",
    "HAS": "Hasbro",
    "MGM": "MGM Resorts",
    "CZR": "Caesars Entertain",
    "WYNN": "Wynn Resorts",
    "RL": "Ralph Lauren",
    "ETSY": "Etsy",
    "MHK": "Mohawk Industries",
    # ── XLP Constituents ──────────────────────────────────────
    "CL": "Colgate-Palmolive",
    "MO": "Altria",
    "TGT": "Target",
    "GIS": "General Mills",
    "SYY": "Sysco",
    "KMB": "Kimberly-Clark",
    "STZ": "Constellation Brands",
    "HSY": "Hershey",
    "CHD": "Church & Dwight",
    "MKC": "McCormick",
    "CAG": "Conagra",
    "CLX": "Clorox",
    "SJM": "J.M. Smucker",
    "TSN": "Tyson Foods",
    "HRL": "Hormel Foods",
    "ADM": "Archer-Daniels",
    "KR": "Kroger",
    "WBA": "Walgreens",
    "TAP": "Molson Coors",
    "CPB": "Campbell's",
    "LW": "Lamb Weston",
    "EL": "Estee Lauder",
    "KVUE": "Kenvue",
    "BG": "Bunge Global",
    "FDP": "Fresh Del Monte",
    "CASY": "Casey's General",
    "USFD": "US Foods",
    # ── IWM Constituents ──────────────────────────────────────
    "BE": "Bloom Energy",
    "SFM": "Sprouts Farmers",
    "FN": "Fabrinet",
    "CRDO": "Credo Technology",
    "NXT": "Nextracker",
    "CDE": "Coeur Mining",
    "SATS": "EchoStar",
    "INSM": "Insmed",
    "HL": "Hecla Mining",
    "FTAI": "FTAI Aviation",
    "GH": "Guardant Health",
    "IONQ": "IonQ",
    "CRS": "Carpenter Tech",
    "ATI": "ATI Inc",
    "HIMS": "Hims & Hers",
    "STRL": "Sterling Infra",
    "AVAV": "AeroVironment",
    "DRS": "Leonardo DRS",
    "PLNT": "Planet Fitness",
    "CORT": "Corcept Therapeut",
    "EAT": "Brinker Intl",
    "MOD": "Modine Mfg",
    "DUOL": "Duolingo",
    "BOOT": "Boot Barn",
    "CALM": "Cal-Maine Foods",
    "SKY": "Skyline Champion",
    "PIPR": "Piper Sandler",
    "LNTH": "Lantheus",
    "PCVX": "Vaxcyte",
    "AIT": "Applied Industrial",
    "IESC": "IES Holdings",
    "RHP": "Ryman Hospitality",
    "GKOS": "Glaukos",
    "NOVT": "Novanta",
    "WDFC": "WD-40",
    "MTH": "Meritage Homes",
    "FNB": "FNB Corp",
    "RMBS": "Rambus",
    "CSWI": "CSW Industrials",
}
